### ISSUE TITLE
Current release is broken, "no module named 'gromp.endpoint'"

### ISSUE THREAD

**Issue by wilhelmagren** [wilhelmagren/gromp#21]
When installing through PyPI and attempting to import gromp you get the following traceback:
```
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gromp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juice/.local/lib/python3.10/site-packages/gromp/__init__.py", line 28, in <module>
    from gromp.endpoint import *
ModuleNotFoundError: No module named 'gromp.endpoint'
```

I suspect this has to do with how submodules are imported, relative to `__init__.py` files. A fix is on the way in a PR.

Otherwise, what could be the problem? Everything works locally and running unittests work...

**Comment by wilhelmagren** [comment]
As of 0.4.1 we now have circular imports instead...
