### ISSUE TITLE
Current relase is broken, "cannot import name 'handler' from partially initialized module 'gromp'"

### ISSUE THREAD

**Issue by wilhelmagren** [wilhelmagren/gromp#24]
```
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gromp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juice/.local/lib/python3.10/site-packages/gromp/__init__.py", line 28, in <module>
    from gromp import handler
ImportError: cannot import name 'handler' from partially initialized module 'gromp' (most likely due to a circular import) (/home/juice/.local/lib/python3.10/site-packages/gromp/__init__.py)
```

We have circular imports... but why?

The `handler` module does not depend on any imports from any other submodules of the lib.

Neither does the `url` submodule...

Should there be no imports in the `__init__` file?

**Comment by wilhelmagren** [comment]
I think a rewrite on the `url` submodule's are needed. They should be implemented under `endpoint` to avoid circular imports.

Also, consider renaming to `api` which makes more sense...

**Comment by wilhelmagren** [comment]
Resolved, see latest commits on main.
